'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { ExampleNavbarTwo } from "@/components/Navbar";
import { CartProvider } from "../context/CartContext.js"; 
import { useRouter } from 'next/navigation'
import CartIcon from "@/components/fixedCart";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();

  
  const isAdminRoute = router.pathname == "/admin";

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Conditionally render ExampleNavbarTwo */}
        {!isAdminRoute && <ExampleNavbarTwo />}
        <CartProvider> {/* Add CartProvider here */}
          {children}
          <CartIcon/>
        </CartProvider>
        {!isAdminRoute &&  <Footer />}
       
      </body>
    </html>
  );
}
